version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rengifo_db
    restart: always
    environment:
      POSTGRES_USER: admin_rengifo
      POSTGRES_PASSWORD: rengifo_planillaspago-826
      POSTGRES_DB: db_planillas_pago_rengifo
    ports:
      - "5454:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rengifo_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: rengifo_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rengifo.com
      PGADMIN_DEFAULT_PASSWORD: rengifo_planillaspago-826
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - rengifo_network

  backend:
    build:
      context: ./backend
    container_name: rengifo_backend
    restart: always
    environment:
      POSTGRES_SERVER: db
      POSTGRES_USER: admin_rengifo
      POSTGRES_PASSWORD: rengifo_planillaspago-826
      POSTGRES_DB: db_planillas_pago_rengifo
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./backend/exports:/app/exports
    depends_on:
      - db
    networks:
      - rengifo_network

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://Rengifo_Ltda:8000
    container_name: rengifo_frontend
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://Rengifo_Ltda:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - rengifo_network

networks:
  rengifo_network:
    driver: bridge

volumes:
  pgdata:
