"""Add users table

Revision ID: 05c1e84fece2
Revises: 26218f915572
Create Date: 2026-08-20 11:29:09.480666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c1e84fece2'
down_revision: Union[str, Sequence[str], None] = '26218f915572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    schema='public'
    )
    op.create_index(op.f('public_users_email_idx'), 'users', ['email'], unique=True, schema='public')
    op.create_index(op.f('public_users_id_idx'), 'users', ['id'], unique=False, schema='public')
    op.create_index(op.f('public_users_username_idx'), 'users', ['username'], unique=True, schema='public')
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_code', sa.String(length=50), nullable=True),
    sa.Column('documento_identidad', sa.String(length=50), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('nacionalidad', sa.String(length=50), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('ocupacion', sa.String(length=100), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('haber_basico', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('employees_pkey')),
    schema='tenant'
    )
    op.create_index(op.f('tenant_employees_documento_identidad_idx'), 'employees', ['documento_identidad'], unique=True, schema='tenant')
    op.create_index(op.f('tenant_employees_id_idx'), 'employees', ['id'], unique=False, schema='tenant')
    op.create_table('payrolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payrolls_pkey')),
    schema='tenant'
    )
    op.create_index(op.f('tenant_payrolls_id_idx'), 'payrolls', ['id'], unique=False, schema='tenant')
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('dias_pagados', sa.Integer(), nullable=True),
    sa.Column('horas_pagadas', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('haber_basico', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bono_antiguedad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bono_produccion', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('subsidio_frontera', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('trabajo_extraordinario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pago_dominical', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('otros_bonos', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_ganado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('aporte_gestora', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rc_iva', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('anticipos', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('otros_descuentos', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_descuentos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('liquido_pagable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['tenant.employees.id'], name=op.f('payslips_employee_id_fkey')),
    sa.ForeignKeyConstraint(['payroll_id'], ['tenant.payrolls.id'], name=op.f('payslips_payroll_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payslips_pkey')),
    schema='tenant'
    )
    op.create_index(op.f('tenant_payslips_id_idx'), 'payslips', ['id'], unique=False, schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('tenant_payslips_id_idx'), table_name='payslips', schema='tenant')
    op.drop_table('payslips', schema='tenant')
    op.drop_index(op.f('tenant_payrolls_id_idx'), table_name='payrolls', schema='tenant')
    op.drop_table('payrolls', schema='tenant')
    op.drop_index(op.f('tenant_employees_id_idx'), table_name='employees', schema='tenant')
    op.drop_index(op.f('tenant_employees_documento_identidad_idx'), table_name='employees', schema='tenant')
    op.drop_table('employees', schema='tenant')
    op.drop_index(op.f('public_users_username_idx'), table_name='users', schema='public')
    op.drop_index(op.f('public_users_id_idx'), table_name='users', schema='public')
    op.drop_index(op.f('public_users_email_idx'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    # ### end Alembic commands ###
