"""Add users table

Revision ID: 05c1e84fece2
Revises: 26218f915572
Create Date: 2026-08-20 11:29:09.480666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c1e84fece2'
down_revision: Union[str, Sequence[str], None] = '26218f915572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    schema='public'
    )
    op.create_index(op.f('public_users_email_idx'), 'users', ['email'], unique=True, schema='public')
    op.create_index(op.f('public_users_id_idx'), 'users', ['id'], unique=False, schema='public')
    op.create_index(op.f('public_users_username_idx'), 'users', ['username'], unique=True, schema='public')
    # Tenant tables are already created in the previous migration
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('tenant_payslips_id_idx'), table_name='payslips', schema='tenant')
    op.drop_table('payslips', schema='tenant')
    op.drop_index(op.f('tenant_payrolls_id_idx'), table_name='payrolls', schema='tenant')
    op.drop_table('payrolls', schema='tenant')
    op.drop_index(op.f('tenant_employees_id_idx'), table_name='employees', schema='tenant')
    op.drop_index(op.f('tenant_employees_documento_identidad_idx'), table_name='employees', schema='tenant')
    op.drop_table('employees', schema='tenant')
    op.drop_index(op.f('public_users_username_idx'), table_name='users', schema='public')
    op.drop_index(op.f('public_users_id_idx'), table_name='users', schema='public')
    op.drop_index(op.f('public_users_email_idx'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    # ### end Alembic commands ###
