"""add icon and logo to tenant

Revision ID: 0f353af84314
Revises: 40b55a2869cf
Create Date: 2026-08-27 12:30:10.455422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add icon and logo to tenant

Revision ID: 0f353af84314
Revises: 40b55a2869cf
Create Date: 2026-08-27 12:30:10.455422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f353af84314'
down_revision: Union[str, Sequence[str], None] = '40b55a2869cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('icon', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('logo_base64', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'logo_base64')
    op.drop_column('tenants', 'icon')
    # ### end Alembic commands ###
