"""add_empleador_fields

Revision ID: 40b55a2869cf
Revises: 05c1e84fece2
Create Date: 2026-08-25 11:05:02.384379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b55a2869cf'
down_revision: Union[str, Sequence[str], None] = '05c1e84fece2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('tenants', sa.Column('empleador_nombres', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('empleador_apellido_paterno', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('empleador_apellido_materno', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('empleador_ci', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('empleador_nit', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('logo_base64', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'logo_base64',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('tenants', 'empleador_nit')
    op.drop_column('tenants', 'empleador_ci')
    op.drop_column('tenants', 'empleador_apellido_materno')
    op.drop_column('tenants', 'empleador_apellido_paterno')
    op.drop_column('tenants', 'empleador_nombres')

    # ### end Alembic commands ###
